- .gitignore
- jniLibs/wallet.h
Added wallet.h
Added libraries for i686-linux-android
Added libraries for x86_64-linux-android
Added libraries for armv7-linux-androideabi
Added libraries for aarch64-linux-android
> Android Libraries

- jniLibs/wallet.h
> Updated Header

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/auth/AuthUtil.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/MainActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/SplashActivity.kt
- app/src/main/res/layout/activity_splash.xml
- app/src/main/res/values/strings.xml
Implemented local authentication. Added a separate splash screen activity due to an issue with Android background/windowBackground theme properties.
> Local Authentication & Separate Splash Screen

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/ui/activity/home/BalanceViewController.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/extension/ViewExtensions.kt
- app/src/main/res/layout/activity_home.xml
- app/src/main/res/layout/home_balance_decimal_digit.xml
- app/src/main/res/layout/home_balance_decimal_separator.xml
- app/src/main/res/layout/home_balance_digit.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Fixes tx list cutout issue, resolves tari-project/wallet-android#76. Improves balance digit views. Fixes some typos. Fix orientation to portrait.
> Tx list cutout fix & balance digit view improvements.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/ui/activity/QRScannerActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/res/anim/slide_down.xml
- app/src/main/res/anim/slide_up.xml
- app/src/main/res/layout/activity_qr_scanner.xml
- app/src/main/res/values/strings.xml
Changes:
- Added `QRScannerActivity` which allows QR code scanning and returns data through intent if succeeds.
- Open `QRScannerActivity` on home screen QR button click
> Implement QR code scanner

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- jniLibs/wallet.h
Changed addContact to addUpdateContact.
Updated JNI.
Merge PR #95 first.
> Updated AddContact

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/ui/activity/CreateWalletActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/SplashActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/util/UiUtil.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/res/layout/activity_create_wallet.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Changes: 
- Implement splash and create wallet animation
Remaining:
- Smooth video looping
> Splash screen loading and create wallet

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/log/DebugLog.kt
- app/src/main/res/layout/debug_log.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Added DebugLog activity
Added debug_log_title to strings
Added debug_log xml layout for DebugLog activity
Added getLogFile() to TariWalletService
Added logFilePAth to WalletService
Added grabberContainerViewLongClicked() to HomeActivity
Added DebugLogActivity to AndroidManifest with landscape orientation
> Added Debug Log Activity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
Optimize wallet service functions that involve listing of transactions (pending in/out & completed). FFIWallet.kt auto-formatted.
> Optimize wallet service

- app/src/androidTest/java/com/tari/android/wallet/FFIPublicKeyTests.kt
- app/src/main/cpp/jniPublicKey.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIPublicKey.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
Added jniGetEmoji() and jniFromEmoji() to PublicKey.
Updated jniVerifyMessageSignature().
Added jniImportUTXO() to wallet.
Updated tests.
> Emojis, ImportUTXO

- app/src/androidTest/java/com/tari/android/wallet/FFICommsConfigTests.kt
- app/src/androidTest/java/com/tari/android/wallet/FFIPublicKeyTests.kt
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/CMakeLists.txt
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/cpp/jniTransportType.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICommsConfig.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITransportType.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
Updated CMAKE to remove zmq
Added jniTransportType.cpp
Added FFITransportType.kt
Updated jniWallet.cpp
Update jniCommsConfig.cpp
Updated WalletModule.kt
Updated CommsConfig.kt
Updated tests
> Update ffi for new comms

- app/src/main/java/com/tari/android/wallet/ffi/HexString.kt
> Fixed format of hex string omitting leading zero

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/di/TrackerModule.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/QRScannerActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/profile/WalletInfoActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/IntroductionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/LocalAuthFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteAndSendFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/SendTxSuccessfulFragment.kt
- app/src/main/java/com/tari/android/wallet/util/SharedPrefsWrapper.kt
Integrates Matomo Android library. Introduces Matomo screen view events as defined [here](https://github.com/tari-project/wallet-android/wiki/Matomo-page-ids). Updates shared preferences encryption library.
> Matomo integration & screen view events.

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/ffi/LogFileObserver.kt
Forward FFI log lines to Android Logcat.
> Forward FFI log lines to Android Logcat.

- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
Split signature and nonce from combined string, updated TestnetTariAllocateRequest call
> Fixed faucet request

- app/src/main/cpp/jniPublicKey.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIPublicKey.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
Update for 33 character emoji id
> JNI Update

- app/src/main/res/drawable/gradient_button_bg.xml
- app/src/main/res/layout/fragment_introduction.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
> Improve introduction UI as per zeplin specs

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/jniByteVector.cpp
- app/src/main/cpp/jniCommon.cpp
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/cpp/jniContact.cpp
- app/src/main/cpp/jniPendingInboundTransaction.cpp
- app/src/main/cpp/jniPendingOutboundTransaction.cpp
- app/src/main/cpp/jniPrivateKey.cpp
- app/src/main/cpp/jniTransportType.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFICompletedTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingInboundTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingOutboundTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIStatus.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITestWallet.kt
- app/src/main/java/com/tari/android/wallet/model/CompletedTx.kt
- app/src/main/java/com/tari/android/wallet/model/PendingInboundTx.kt
- app/src/main/java/com/tari/android/wallet/model/PendingOutboundTx.kt
- app/src/main/java/com/tari/android/wallet/model/Status.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
Corrected necessary JNI lints.
Implemeneted status for pending transactions from JNI through kotlin.
Udated wallet services and parcebles for statuses.
Updated mine and broadcast tx methods.
Updated tests.
> Pending Transaction Status

- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateWalletFragment.kt
- app/src/main/res/layout/fragment_create_wallet.xml
- app/src/main/res/values/dimens.xml
> Create wallet ui improvement

- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/res/drawable/home_grabber.xml
- app/src/main/res/layout/activity_home.xml
- app/src/main/res/layout/home_dialog_testnet_tari_received.xml
- app/src/main/res/layout/home_tx_list_header.xml
- app/src/main/res/layout/home_tx_list_item.xml
- app/src/main/res/values/dimens.xml
> Home UI improvement

- app/src/main/cpp/jniByteVector.cpp
- app/src/main/cpp/jniCollections.cpp
- app/src/main/cpp/jniCommon.cpp
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/cpp/jniCompletedTransaction.cpp
- app/src/main/cpp/jniContact.cpp
- app/src/main/cpp/jniPendingInboundTransaction.cpp
- app/src/main/cpp/jniPendingOutboundTransaction.cpp
- app/src/main/cpp/jniPrivateKey.cpp
- app/src/main/cpp/jniPublicKey.cpp
- app/src/main/cpp/jniTransportType.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIByteVector.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICommsConfig.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICompletedTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICompletedTxs.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIContact.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIContacts.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingInboundTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingInboundTxs.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingOutboundTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingOutboundTxs.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPrivateKey.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPublicKey.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITestWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITransportType.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
Added GetPointerField and SetPointerField to common.cpp
Removed passing pointer values to Kotlin from JNI and instead assigned pointers returned from FFI directly to object passed into JNI.
> JNI Improvement

- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/res/layout/activity_tx_detail.xml
- app/src/main/res/values/dimens.xml
> Tx detail ui improvement

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
Fixes crash when scanning a QR code or pasting an emoji id
> QR Scan and Emoji Paste Fix

- app/src/main/aidl/com/tari/android/wallet/service/TariWalletServiceListener.aidl
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListenerAdapter.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/profile/WalletInfoActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteAndSendFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/util/WalletUtil.kt
- app/src/main/res/layout/activity_tx_detail.xml
Fixes tari-project/wallet-android#180. Fixes tari-project/wallet-android#182. Partially fixes tari-project/wallet-android#181.
> Service, deep link & UI fixes.

- app/src/main/aidl/com/tari/android/wallet/model/Model.aidl
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletServiceListener.aidl
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/model/RxId.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
Fixed jniAddBaseNodePeer to use an object for PublicKey
Fixed display of Wallet Info
> Misc Fixes

- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/res/values/strings.xml
> Outgoing transaction details field name error.

- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
> Fix outgoing transaction detail doesn't show transaction fee

- app/src/main/AndroidManifest.xml
> Remove RTL support

- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/res/layout/tx_detail_fee_tooltip.xml
- app/src/main/res/values/strings.xml
> Show tooltip on tx fee click

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/di/TorModule.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIByteVector.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/HexString.kt
- app/src/main/java/com/tari/android/wallet/tor/TorConfig.kt
- app/src/main/java/com/tari/android/wallet/util/SharedPrefsWrapper.kt
Stores Tor identity in the shared preferences and reuses on next wallet instantiation. Solution for #270.
> Tor identity persistence.

- app/src/main/aidl/com/tari/android/wallet/service/TariWalletService.aidl
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletServiceListener.aidl
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListenerAdapter.kt
- app/src/main/java/com/tari/android/wallet/model/TxId.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
Introduces store & forward updates to FFI, service and UI layers.
> FFI store & forward updates.

- app/src/androidTest/java/com/tari/android/wallet/HexStringTests.kt
- app/src/androidTest/java/com/tari/android/wallet/NetAddressStringTests.kt
- app/src/main/cpp/jniWallet.cpp
Fixed outdated HexString test
Fixed outdated NetAddressString test
Updated jniWallet.cpp to fix const correctness in log path pointer
> Fixed Some Tests

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
Refactored loops to test all indices.
Test functionality remains otherwise the same.
> Refactored Wallet Test

- app/src/main/res/values/strings.xml
tari-project/wallet-android#286
Change the privacy policy and user agreement URLs on the splash screen
> Change the privacy policy and user agreement URL links

- app/src/main/java/com/tari/android/wallet/ui/activity/home/adapter/TxHeaderViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/adapter/TxListAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/res/drawable/background_transaction_state.xml
- app/src/main/res/drawable/background_transaction_state_dimmer.xml
- app/src/main/res/layout/activity_tx_detail.xml
- app/src/main/res/layout/home_tx_list_header.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
tari-project/wallet-android#298
Remove progress bar from tx list "in progress" header
Add status for tx details
> Store & Forward UI/UX corrections

- app/build.gradle
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/res/values/strings.xml
Added log_debug_message to jniWallet.cpp and logMessage to wallet.kt. This enables logging of client messages to FFI logs.
> Added FFI method

- app/src/main/res/values/strings.xml
tari-project/wallet-android#307
Remove all mentions of testnet and Tari (as a currency unit)
> Replace testnet and Tari mentions

- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
tari-project/wallet-android#300
> Show contact aliases in push notification titles

- app/src/main/java/com/tari/android/wallet/network/NetworkConnectionStateReceiver.kt
- app/src/main/res/values/strings.xml
Less strict internet connectivity check per tari-project/wallet-android#322. A copy fix for one of the connection error dialogs.
> Less strict internet connectivity check.

- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
tari-project/wallet-android#298
Account for pending status during TX status representation
> Show "waiting for sender to complete transaction" when inbound TX status is either `pending` or `completed`

- app/src/main/java/com/tari/android/wallet/model/CompletedTx.kt
- app/src/main/java/com/tari/android/wallet/model/PendingInboundTx.kt
- app/src/main/java/com/tari/android/wallet/model/PendingOutboundTx.kt
- app/src/main/java/com/tari/android/wallet/model/Tx.kt
- app/src/main/java/com/tari/android/wallet/model/WalletError.kt
- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/animation/Animations.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/ErrorDialog.kt
- app/src/main/res/drawable/home_tx_value_canceled_bg.xml
- app/src/main/res/layout/activity_tx_detail.xml
- app/src/main/res/layout/dialog_cancel_tx.xml
- app/src/main/res/layout/dialog_error.xml
- app/src/main/res/layout/tx_canceled_notification.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
tari-project/wallet-android#295
Implement "Cancel transaction" CTA (TX list updates, push notifications and TX details statuses is yet to come)
> Cancel pending outbound TX CTA

- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/di/TrackerModule.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/ConsoleLogTracker.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/MatomoTracker.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/Tracker.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/profile/WalletInfoActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/qr/QRScannerActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/IntroductionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/LocalAuthFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/FinalizeSendTxFragment.kt
tari-project/wallet-android#331
Abstract tracker implementation and inject mamoto only for not debug builds
> Disable Matomo for debug builds

- app/src/main/java/com/tari/android/wallet/infrastructure/ConsoleLogTracker.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/MatomoTracker.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/Tracker.kt
tari-project/wallet-android#331
Abstract tracker implementation and inject mamoto only for not debug builds
> Add licence headers for tracker files

- secret-example.properties
Malformed default DSN crashes the app. Default dummy value fixed.
> Correctly formed default Sentry DSN.

- app/src/main/java/com/tari/android/wallet/ui/activity/send/SendTariActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/FinalizeSendTxFragment.kt
Remove crash on SendTariActivity context configuration change, remove weak reference access whereas strong reference is already present, add null-safety for animation listeners
> Remove crash on SendTariActivity context configuration change

- app/src/main/res/values/strings.xml
Copy changes per tari-project/wallet-android#307 and tari-project/wallet-android#346.
> Copy fixes.

- app/build.gradle
- build.gradle
Remove unused coroutines and viewmodel-ext dependencies, also update kotlin plugin version
> Refine gradle config scripts

- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
Disables shake detection in background mode per tari-project/wallet-android#373.
> Prevent the opening of debug screen in background mode.

- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
Preserve already existing HomeActivity during notification navigation
Signed-off-by: Andrey Ilyunin <orkay255@gmail.com>
> Preserve already existing HomeActivity during notification navigation

- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListenerAdapter.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
tari-project/wallet-android#376
Fix the bug with incorrect sender id on TX live update
> Fix the bug with incorrect sender id on TX live update

- app/build.gradle
- app/src/main/aidl/com/tari/android/wallet/model/Model.aidl
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletService.aidl
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletServiceListener.aidl
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListenerAdapter.kt
- app/src/main/java/com/tari/android/wallet/model/RequestId.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/CustomScrollView.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/UpdateProgressViewController.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/adapter/TxListAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/send/SendTariActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/FinalizeSendTxFragment.kt
Improves the responsiveness of the transaction list and the performance of wallet callback functions and event handlers. Solutions for tari-project/wallet-android#374 & tari-project/wallet-android#353. Various structural and readability improvements. Updates Tor binaries to 0.2.4.7.
> UI load test concurrency fixes, structural & readability updates, Tor binary update.

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
Fix https://sentry.tarilabs.com/organizations/sentry/issues/91
> Fix add recipient crash

- app/src/main/res/values/strings.xml
tari-project/wallet-android#395
Change the text line
> Change the text line for "waiting for recipient"

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/service/notification/NotificationService.kt
- app/src/privacy/java/com/tari/android/wallet/service/notification/NoOpNotificationService.kt
- app/src/regular/java/com/tari/android/wallet/di/RESTModule.kt
- app/src/regular/java/com/tari/android/wallet/service/notification/PushNotificationRESTService.kt
- app/src/regular/java/com/tari/android/wallet/service/notification/PushNotificationRequestBody.kt
- secret-example.properties
tari-project/wallet-android#399
Add an api key as a part of push notifications signature
> Add an api key as a part of push notifications signature

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
Added jniCoinSplit() to  wallet.cpp
Added jniCoinSplit() and coinSplit() to FFIWallet.kt
Linked to PR tari-project/tari#1895
> Updated FFI - Coin Split

- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/adapter/TxListAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/res/drawable/view_elevation_bottom_gradient.xml
- app/src/main/res/layout/dialog_store.xml
- app/src/main/res/values/strings.xml
- app/src/regular/java/com/tari/android/wallet/service/notification/PushNotificationRESTService.kt
- app/src/regular/java/com/tari/android/wallet/service/notification/PushNotificationResponseBody.kt
- build.gradle
Solution for cancelled tx recipient public key issue tari-project/wallet-android#414. Adds elevation views to top and bottom controls in store web view dialog. Removes some unnecessary logs. Fixes send tx push notification response field name. Bump build number to 115.
> Transaction cancelled callback public key bug fix & some other fixes/improvements.

- app/src/main/java/com/tari/android/wallet/ui/activity/home/CustomScrollView.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/res/layout/activity_home.xml
Improves transaction list nested scrolling behaviour: solution for tari-project/wallet-android#353.
> Transaction list scrolling behaviour glitch fix.

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
User can now tap the emoji id banner or the button to paste the emoji id in the clipboard. Solution for tari-project/wallet-android#424.
Fixes a minor UI bug that caused the soft keyboard to not show when there's an emoji id in the clipboard.
> Add Recipient: tap Emoji ID to paste.

- app/src/main/aidl/com/tari/android/wallet/service/TariWalletService.aidl
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
Remove contact by removing alias in transaction details screen per tari-project/wallet-android#287.
> Remove contact (alias).

- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
https://sentry.tarilabs.com/organizations/sentry/issues/129
> Update balance info only if the corresponding ui tree was initialized

- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
https://sentry.tarilabs.com/organizations/sentry/issues/108
> Initialize expiration check only after the FFIWallet was initialized

- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/LocalAuthFragment.kt
https://sentry.tarilabs.com/organizations/sentry/issues/137
> Add nullable context preservation for local auth fragment 

- app/build.gradle
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICommsConfig.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/restore/WalletRestoreActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
- app/src/main/java/com/tari/android/wallet/util/SharedPrefsWrapper.kt
- build.gradle
- download-jni-binaries.gradle
Introduces power consumption modes and migrates private key to the wallet database per the latest FFI updates. Changes base node on sync failure tari-project/wallet-android#439. Bump version number.
> Power consumption mode. Comms private key migration to database. Base node round robin.

- app/src/main/java/com/tari/android/wallet/ui/activity/settings/SettingsActivity.kt
- app/src/main/res/anim/enter_from_bottom.xml
- app/src/main/res/anim/enter_from_top.xml
- app/src/main/res/anim/exit_to_bottom.xml
- app/src/main/res/anim/exit_to_top.xml
- app/src/main/res/values/strings.xml
Overrides settings activity appear and disappear anims, changes contribution link per comments on tari-project/wallet-android#407.
> Settings activity appear and disappear animations.

- build.gradle
- download-jni-binaries.gradle
Version to 0.2.1. Update FFI dependency. FFI 0.13.1. Improves network connectivity.
> Bump version. Update FFI.

- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/BugReportingService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/debug/DebugLogFragment.kt
- app/src/main/res/values/strings.xml
- app/src/privacy/java/com/tari/android/wallet/ui/fragment/settings/AllSettingsFragment.kt
- app/src/privacy/res/layout/fragment_all_settings.xml
- app/src/regular/java/com/tari/android/wallet/di/BackupAndRestoreComponent.kt
- app/src/regular/java/com/tari/android/wallet/ui/fragment/settings/AllSettingsFragment.kt
- app/src/regular/res/layout/fragment_all_settings.xml
Adds "Report a bug" item into the settings menu per tari-project/wallet-android#452.
> Bug reporting option in settings menu

- app/build.gradle
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/jniCompletedTransaction.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFICompletedTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- build.gradle
- download-jni-binaries.gradle
- gradle/wrapper/gradle-wrapper.properties
FFI v0.14.0-rc, Build Tools and Gradle updates.
> FFI v0.14.0-rc update.

- .github/workflows/pull-request-test-workflow.yml
- build.gradle
Updates JNI binaries to v0.15.1 and app version to 0.2.2.
> JNI binaries v0.15.1 & App v0.2.2

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletServiceListener.aidl
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListenerAdapter.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/UpdateProgressViewController.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
Improves wallet callback listener interface and wallet events by mapping callback parameter types to proper types in the application domain.
> Better wallet listener interface and wallet event data types.

- app/src/main/java/com/tari/android/wallet/model/TxId.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
tari-project/wallet-android#416
> Retrieve the most recent TX state in TxDetailActivity before displaying it

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/BackupSettingsFragment.kt
- app/src/main/res/layout/dialog_turn_off_backups_will_be_deleted_warning.xml
- app/src/main/res/values/strings.xml
tari-project/wallet-android#475
>  Show warning dialog before disabling the backups

- app/src/main/res/layout/fragment_wallet_backup_settings.xml
tari-project/wallet-android#480
> Align toggle with the arrow

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/LocalBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/ChooseRestoreOptionFragment.kt
- app/src/regular/java/com/tari/android/wallet/infrastructure/backup/GoogleDriveBackupStorage.kt
Enables automated (encrypted) backups after a restore per tari-project/wallet-android#479.
> Enable backups after restore.

- app/src/main/java/com/tari/android/wallet/event/EventBus.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/BackupSettingsFragment.kt
tari-project/wallet-android#481
> Hide "Back Up Now" button if the backup is up to date

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupAndRestoreException.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/BackupSettingsFragment.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/privacy/java/com/tari/android/wallet/di/BackupAndRestoreModule.kt
- app/src/privacy/res/values/strings.xml
- app/src/regular/java/com/tari/android/wallet/di/BackupAndRestoreModule.kt
- app/src/regular/java/com/tari/android/wallet/infrastructure/backup/GoogleDriveBackupStorage.kt
- app/src/regular/res/values/strings.xml
Displays backup storage full dialog for user-initiated backup and push notification for scheduled backup per tari-project/wallet-android#482 and tari-project/wallet-android#485.
> Google Drive storage full modal (user-triggered backup) and push notification (scheduled backup).

- app/src/main/res/values/strings.xml
- app/src/privacy/res/values/strings.xml
- app/src/regular/res/values/strings.xml
Google Drive backup error copy correction per tari-project/wallet-android#483 and tari-project/wallet-android#484.
> Google Drive backup error copy correction

- app/src/main/java/com/tari/android/wallet/ui/fragment/debug/BaseNodeConfigFragment.kt
Support all onion address types in debug base node setting screen per tari-project/wallet-android#466.
> Base node setting screen onion address versions support

- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/settings/SettingsActivity.kt
tari-project/wallet-android#501
> Navigate to all settings from wallet backup prompt

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/debug/BaseNodeConfigFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/ChooseRestoreOptionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/EnterRestorationPasswordFragment.kt
- app/src/main/res/values/strings.xml
- build.gradle
Create backup password copy fix tari-project/wallet-android#429. Wallet restore password entry CTA button enabled/disabled fix tari-project/wallet-android#474. Settings and backup settings screen backup state display fix tari-project/wallet-android#509.
> Various backup & restore fixes

- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxListAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxViewHolder.kt
Update transaction list timestamp in real time per tari-project/wallet-android#517.
> Transaction list update transaction timestamp in real time.

- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/AllSettingsFragment.kt
tari-project/wallet-android#511
> Authorize backup settings page opening by biometric check

- app/src/main/res/values/strings.xml
- app/src/privacy/res/values/strings.xml
- app/src/regular/res/values/strings.xml
tari-project/wallet-android#514
> Separate backup prompt warning strings for private and regular builds

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/util/SharedPrefsWrapper.kt
tari-project/wallet-android#512
> Delete local backups on backups disable from backup settings page

- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListFragment.kt
tari-project/wallet-android#513
> Show correct backup prompt modal for threshold Tari values

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateWalletFragment.kt
tari-project/wallet-android#523
> Remove double memfree in jniCreateWallet

- app/src/main/java/com/tari/android/wallet/event/EventBus.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/store/EventsPropagatingWebViewClient.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/store/StoreFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/store/WebViewEventListener.kt
- app/src/main/res/layout/fragment_store.xml
Reload store page on internet connection resume in case of error
Make controls hidden and shown accordingly to the scroll direction
> Improve store page

- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailsActivity.kt
- app/src/main/res/layout/activity_tx_details.xml
- app/src/main/res/layout/fragment_tx_list.xml
- build.gradle
Transaction details should display the transaction from the list if it's opened from the list, or load the transaction fresh if it's opened through a push notification. Transaction details small layout fix. Bump build number.
> Transaction details minor improvements.

- app/src/main/java/com/tari/android/wallet/ui/activity/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/SplashActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
tari-project/wallet-android#547
> Process deeplink on first app launch

- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
tari-project/wallet-android#318
> Cleanup logs once in half an hour upper bounded by 30 MB

- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxViewHolder.kt
- app/src/main/res/layout/activity_tx_details.xml
- app/src/main/res/layout/home_tx_list_item.xml
- app/src/main/res/values/colors.xml
tari-project/wallet-android#558
tari-project/wallet-android#559
> Show canceled TX status in the TX list and change the status color at TX details page

- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
tari-project/wallet-android#537
> Fix a duplicated pending inbound transaction after wallet restoration

- app/src/main/res/layout/tx_canceled_notification.xml
- app/src/main/res/layout/tx_notification.xml
- app/src/main/res/values/colors.xml
tari-project/wallet-android#574
> Change notifications text color

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
tari-project/wallet-android#594
> Prevent l character from removal if not emoji id is being entered

- app/src/main/java/com/tari/android/wallet/ui/fragment/store/EventsPropagatingWebViewClient.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/store/StoreFragment.kt
tari-project/wallet-android#584
> Open non-store links in the external browser

- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListFragment.kt
- app/src/main/res/values/strings.xml
Improves "too many faucet requests" error message. Related to tari-project/wallet-android#603.
> Better error message for too many faucet requests.

- app/build.gradle
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletService.aidl
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- build.gradle
Introduces JNI, service and test updates for the key-value storage support that came with the FFI library version 0.16.8.
> Key-value storage JNI, service and test updates.

- app/src/androidTest/java/com/tari/android/wallet/FFICommsConfigTests.kt
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICommsConfig.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
Linked to PR: 
https://github.com/tari-project/tari/pull/2748
> Added saf message duration

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/res/layout/fragment_add_amount.xml
- app/src/main/res/values/strings.xml
Also refactored AmountCheckRunnable for enhancing readability
> Added constant Wallet Balance on AddAmountFragment 

- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/di/PresentationModule.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/repository/GiphyKeywordsRepository.kt
Added several giphy keywords into carousel into AddNoteFragment
> Added several giphy keywords into carousel

- app/src/main/java/com/tari/android/wallet/ui/component/FullEmojiIdViewController.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteFragment.kt
- app/src/main/res/drawable/emoji_id_long_press_hint_bg.xml
- app/src/main/res/layout/fragment_add_amount.xml
- app/src/main/res/layout/fragment_add_note.xml
- app/src/main/res/layout/fragment_wallet_info.xml
- app/src/main/res/layout/view_full_emoji_id.xml
- app/src/main/res/values/strings.xml
Also extract full emoji id view and make rafactoring
> Create long-press hint into full emoji view

- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListFragment.kt
Fix bugs with updating tx on main list on background and foreground states
Also explore that tx can skip mined_unconfirmed state and fixed it too
> Fix bugs with updating tx list

- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailsActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/component/FullEmojiIdViewController.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteFragment.kt
- app/src/main/res/layout/activity_tx_details.xml
- app/src/main/res/layout/fragment_add_amount.xml
Refactored TxDetailActivity with new FullEmojiIdViewController
Changed calculation top offset in controller
> Refactored TxDetailActivity with new FullEmojiIdViewController

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/di/YATModule.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/yat/adapter/YatAdapter.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/yat/adapter/YatAdapterImpl.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/SplashActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/onboarding/OnboardingFlowActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/createWallet/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/createWallet/WalletCreationViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/WalletRestoringFragment.kt
1. Integrated deeplinks on buying Yat flow
2. Revive backup wallet flow
3. Revive restore wallet flow
> Revived backup and restore flows, intergated Yat-lib v1.0.5 with deeplinks on buying flow

- app/build.gradle
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/SharedPrefsRepository.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
- app/src/regular/java/com/tari/android/wallet/di/BackupAndRestoreModule.kt
- app/src/regular/java/com/tari/android/wallet/infrastructure/backup/GoogleDriveBackupStorage.kt
- build.gradle
1. Wrapped FFI new methods
2. Added FFI passphrase on SecuredPrefs
3. Implemented database encryption using new FFI methods
1. Encrypt DB if it was only created or the application was updated
2. Decrypt DB before backup and encrypt after
3. Clean passphrase after the wallet has been deleted
> Database encryption

- app/src/androidTest/java/com/tari/android/wallet/FFIByteVectorTests.kt
- app/src/androidTest/java/com/tari/android/wallet/FFICommsConfigTests.kt
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICommsConfig.kt
Requires:
https://github.com/tari-project/tari/pull/3178
> Add basis for network selection through FFI.

- app/src/androidTest/java/com/tari/android/wallet/FFITransportTypeTest.kt
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/cpp/jniTransportType.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/SharedPrefsRepository.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICommsConfig.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITransportType.kt
- build.gradle
* Updated FFI library to 0.17.3
* Fixed compilation errors
* Tested
> Update FFI library to 0.17.3

- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/application/WalletState.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupAndRestoreException.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/LocalAuthFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/res/layout/fragment_choose_restore_option.xml
- app/src/main/res/values/strings.xml
- build.gradle
* Changed WalletState from Enum to SealedClass
* Added Failed to WalletState to have a state when wallet creating was failed
* Remove partial backup on backup flow
* Added trial wallet start on recovery flow to prevent wallet creation error(like 114 and 420)
* Added dialog for user explaining 114 error and how he can deal with it
> Fixing restoration flow

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/SharedPrefsRepository.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyManager.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/SplashActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/error/ErrorDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/walletRestoringFromSeedWords/WalletRestoringFromSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/walletRestoringFromSeedWords/WalletRestoringFromSeedWordsViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/res/values/strings.xml
- build.gradle
* Updated UI dependencies to eliminate Google Play warnings about Non-SDK API
* Fixed not clearing Background Service setting
* Fixed crash on Tor shutdown
* Fixed crash on Stopping background service
* Added base node iteration on recovery from seed words
* Added confirmation dialog on authentication to eliminate wallet lock
* Fixed crash after clearing application data into settings
> Crash fixes

- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/component/loadingButton/LoadingButtonState.kt
- app/src/main/java/com/tari/android/wallet/ui/component/loadingButton/LoadingSwitchView.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/inProgress/ProgressDialogArgs.kt
- app/src/main/java/com/tari/android/wallet/ui/extension/ViewExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsViewModel.kt
- app/src/main/res/layout/fragment_wallet_input_seed_words.xml
- app/src/main/res/layout/view_progress_button.xml
* Extracted progress button into a separate entity
* Added loading state on Wallet recovery
* Added ability to paste whole seed phrase with " " and "\n" delimiters
* Added click throttling into whole recovery process
> Added ability to paste text

- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/application/WalletState.kt
- app/src/main/java/com/tari/android/wallet/application/baseNodes/BaseNodes.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
- app/src/main/res/layout/fragment_tx_list.xml
* Fixed bug when the application crashed on creation flow because of EventBus.walletState subscription. Running state was published when the service wasn't prepared
* Added available balance into common animations
* Fixed bug on home screen onboarding flow when onboarding text and empty list text appeared simultaneously
* Added base node start sync conditions
* Fixed bug on the main screen when subscription executed earlier then viewModel the property was initialized and appeared connection to the service
> Application review, fixing bugs

- .github/workflows/pr_title.yml
This PR adds a lint check for pull request titles to ensure they conform to the conventional commits specification.
This will help ensure that these follow the same convention across repositories.
This has been carried over from https://github.com/tari-project/tari.
> feat: add pull request title check

- app/src/main/java/com/tari/android/wallet/ui/dialog/backup/BackupWalletDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
* Fixed missing resource into backup dialog
> fix: fixed missing resource

- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/SharedPrefsRepository.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationModule.kt
- app/src/main/java/com/tari/android/wallet/di/PresentationModule.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/LocalBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/backup/BackupSettingsRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/EnterCurrentPasswordFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupSettings/BackupSettingsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupSettings/BackupSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
- app/src/privacy/java/com/tari/android/wallet/di/BackupAndRestoreModule.kt
- app/src/regular/java/com/tari/android/wallet/di/BackupAndRestoreModule.kt
- app/src/regular/java/com/tari/android/wallet/infrastructure/backup/GoogleDriveBackupStorage.kt
* Added delay on backup dialogs
* Extracted backup settings into separate repository
> feat: added delay on backup dialog

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/model/Contact.kt
- app/src/main/java/com/tari/android/wallet/model/MicroTari.kt
- app/src/main/java/com/tari/android/wallet/model/User.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/error/ErrorDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/activity/SendTariActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/common/TransactionData.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxListener.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizingStep.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/TxFailureReason.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/YatFinalizeSendTxActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
- app/src/main/java/com/tari/android/wallet/yat/YatAdapter.kt
- app/src/main/java/com/tari/android/wallet/yat/YatUser.kt
- app/src/main/res/values/strings.xml
* Added full animated outcoming transaction screen for yat flow
* Refactored finalizing step screeen
> feat: yat integration part 4

- app/src/main/java/com/tari/android/wallet/data/network/NetworkRepositoryImpl.kt
- app/src/main/java/com/tari/android/wallet/data/network/TariNetwork.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationModule.kt
- app/src/main/java/com/tari/android/wallet/service/BootDeviceReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/ServiceRestartBroadcastReceiver.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/res/values/strings.xml
- app/src/regular/java/com/tari/android/wallet/di/RESTModule.kt
* Added faucet url into network settings
* Set null to Igor faucet url
> feat: reworked faucet url for igor and weatherwax

- app/src/androidTest/java/com/tari/android/wallet/FFICommsConfigTests.kt
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/application/DeepLink.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/qr/QRScanData.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/qr/QRScannerActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientViewModel.kt
- app/src/test/java/com/tari/android/wallet/application/DeepLinkTest.kt
- app/src/test/java/com/tari/android/wallet/infrastructure/backup/storage/TariBackupNameValidationPolicyTest.kt
* Fixed QR code scanning bugs
* Fixed tests
> fix: fixed qr code parsing

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientViewModel.kt
- build.gradle
Proguard changed API Dtos names into random. Set constant names
> fix: fixed build proguard behavior

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/model/Contact.kt
- app/src/main/java/com/tari/android/wallet/model/User.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/common/TransactionData.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/YatFinalizeSendTxActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
- app/src/main/java/com/tari/android/wallet/yat/YatAdapter.kt
- app/src/main/java/com/tari/android/wallet/yat/YatUser.kt
- build.gradle
* Some sort of parceble bug inside the system. Solved it using JSON instead of standard tools
* Bump the number
* Update links to production
* Fixed themes on success dialog
> fix: fixed yat parceble bugs

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
Fixed crashes related to android 12 security updates
> feat: android 12 security adaptation

- app/build.gradle
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/AndroidManifest.xml
- app/src/main/cpp/jniSeedWords.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFISeedWords.kt
- app/src/main/java/com/tari/android/wallet/ui/common/LiveDataExtension.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/suggestions/SuggestionState.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/suggestions/SuggestionViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/suggestions/SuggestionViewHolderItem.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/suggestions/SuggestionsAdapter.kt
- app/src/main/res/layout/fragment_wallet_input_seed_words.xml
- app/src/main/res/layout/item_suggestion.xml
- app/src/main/res/values/strings.xml
* Implemented wrapper for a mnemonic list
* Added suggestion on entry flow
* Improve input experience
> feat: improve seed words entry flow

- app/src/main/java/com/tari/android/wallet/yat/YatAdapter.kt
- app/src/test/java/com/tari/android/wallet/infrastructure/backup/storage/TariBackupNameValidationPolicyTest.kt
- build.gradle
> feat: update to 0.21.1

- app/src/test/java/com/tari/android/wallet/application/DeepLinkTest.kt
- build.gradle
> fix: deeplink tests

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoFragment.kt
- app/src/main/java/com/tari/android/wallet/yat/YatAdapter.kt
- build.gradle
Update yat lib and some UI libs
> feat: update yat lib

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientViewModel.kt
- app/src/regular/java/com/tari/android/wallet/infrastructure/backup/GoogleDriveBackupStorage.kt
- build.gradle
* Bumped version for release
* Fixed issue with clipboard manager on sending
* Fixed crash on the first start
> fix: fixed clipboard issue and crash on start

- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/enterRestorationPassword/EnterRestorationPasswordFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/enterRestorationPassword/EnterRestorationPasswordViewModel.kt
- app/src/privacy/java/com/tari/android/wallet/di/BackupAndRestoreModule.kt
> fix: fixed back button on recovery

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientViewModel.kt
> fix: no send button

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/enterRestorationPassword/EnterRestorationPasswordFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientViewModel.kt
- app/src/main/java/com/tari/android/wallet/yat/YatAdapter.kt
- build.gradle
> fix: update yat lib

- app/src/main/java/com/tari/android/wallet/di/ApplicationModule.kt
- app/src/main/java/com/tari/android/wallet/service/BootDeviceReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/ServiceRestartBroadcastReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/WalletServiceLauncher.kt
Fixed boot and restart crashes
> fix: reboot crash

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/networkSelection/NetworkSelectionViewModel.kt
Added condition for network selector action in case not existing wallet
> fix: added condition for network selector action

- app/build.gradle
- app/src/main/cpp/jniBalance.cpp
- app/src/main/cpp/jniByteVector.cpp
- app/src/main/cpp/jniCollections.cpp
- app/src/main/cpp/jniCommsConfig.cpp
- app/src/main/cpp/jniCompletedTransaction.cpp
- app/src/main/cpp/jniCompletedTransactionKernel.cpp
- app/src/main/cpp/jniContact.cpp
- app/src/main/cpp/jniEmojiSet.cpp
- app/src/main/cpp/jniPendingInboundTransaction.cpp
- app/src/main/cpp/jniPendingOutboundTransaction.cpp
- app/src/main/cpp/jniPrivateKey.cpp
- app/src/main/cpp/jniPublicKey.cpp
- app/src/main/cpp/jniSeedWords.cpp
- app/src/main/cpp/jniTransportType.cpp
- app/src/main/cpp/jniUtil.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListener.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> feat: update lib 0 22 1

- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/WordItemViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/WordTextView.kt
- app/src/main/res/drawable/close_error.xml
- app/src/main/res/drawable/restoring_seed_phrase_word_background_error.xml
Added invalid word hint into recovery process
> feat: added error hint into recovery process

- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/IntroductionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/TariVersionModel.kt
- app/src/main/res/layout/fragment_all_settings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/tari/android/wallet/infrastructure/backup/storage/NetworkRepositoryMock.kt
- app/src/test/java/com/tari/android/wallet/infrastructure/backup/storage/TariBackupNameValidationPolicyTest.kt
* Added explorer link into settings
* Added wallet version into settings
> feat: added to settings explorer link and tari wallet version

- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
* Fixed old testnet utxos crash
> fix: suppress crash

- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
> fix: suppress null returning exception

- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/verifySeedPhrase/SeedPhrase.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/verifySeedPhrase/VerifySeedPhraseFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/verifySeedPhrase/VerifySeedPhraseViewModel.kt
> feat: sorted recovery list

- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/verifySeedPhrase/SelectableWordTextView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/verifySeedPhrase/VerifySeedPhraseFragment.kt
- app/src/main/res/layout/fragment_verify_seed_phrase.xml
- app/src/main/res/layout/view_confirm_word.xml
- app/src/main/res/values/styles.xml
* Added UI that show to user his ability to delete word
* Improved UI interaction
> feat: verifying seed phrase aligning

- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListener.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/service/baseNode/BaseNodeState.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/ConnectionIndicatorViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/ui/UpdateProgressViewController.kt
- app/src/main/res/values/strings.xml
* Changed connectivity base node status
> feat: changed connectivity format

- build.gradle
Signed-off-by: Aleksandr Vakhtin <alexandr@tari.com>
> feat: version update

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/activity/SendTariActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountListener.kt
> feat: skip note with one side payment transaction

- app/src/main/java/com/tari/android/wallet/model/CompletedTransactionKernel.kt
- app/src/main/java/com/tari/android/wallet/model/CompletedTx.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsViewModel.kt
- app/src/main/res/layout/fragment_tx_details.xml
- app/src/main/res/values/strings.xml
Description:
* Added explorer link
* Some changes into tx detail screen
> feat: added explorer link

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkViewModel.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/baseNode/BaseNodeDto.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/addCustomBaseNode/AddCustomBaseNodeDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/addCustomBaseNode/AddCustomBaseNodeDialogArgs.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/confirm/ConfirmDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/debug/baseNodeConfig/changeBaseNode/ChangeBaseNodeFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/debug/baseNodeConfig/changeBaseNode/ChangeBaseNodeViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/debug/baseNodeConfig/changeBaseNode/adapter/BaseNodeViewHolderItem.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/IntroductionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/enterRestorationPassword/EnterRestorationPasswordFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsNavigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/restore/WalletRestoreActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/restore/WalletRestoreRouter.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/walletRestoring/WalletRestoringFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/walletRestoringFromSeedWords/WalletRestoringFromSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientFragment.kt
- app/src/main/res/drawable/background_gray_round.xml
- app/src/main/res/layout/activity_wallet_backup.xml
- app/src/main/res/layout/fragment_wallet_input_seed_words.xml
- app/src/main/res/layout/view_custom_base_node_full_description.xml
- app/src/main/res/values/strings.xml
* Added missed custom base node popup
* Added ability to select base node before recovery
> feat: added ability to select base node before recovery

- app/src/main/java/com/tari/android/wallet/application/Network.kt
- app/src/main/java/com/tari/android/wallet/data/repository/CommonRepository.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/SharedPrefsRepository.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/baseNode/BaseNodeSharedRepository.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NetworkRepositoryImpl.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NetworkUtils.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NoSupportedNetworkException.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/tariSettings/TariSettingsSharedRepository.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/testnetFaucet/TestnetFaucetRepository.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/tor/TorSharedRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/BackupSettingsRepository.kt
- app/src/main/java/com/tari/android/wallet/yat/YatSharedRepository.kt
Description:
* Mocked getNetworkName catching
* Extract formatKey for repositories into utils
> fix: sentry display name exception

- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
Description: 
* Delete dead code affected Xiaomi permission problem
> fix: xiaomi permission

- app/src/main/java/com/tari/android/wallet/ui/extension/ViewExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/extension/ViewHolderExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsViewModel.kt
Description:
* Fixed bug with not loaded requireConfirmationCount
* Checked layout of that screen on several screen sizes, looks ok on all of them
> fix: tx details

- app/src/main/java/com/tari/android/wallet/ui/activity/SplashActivity.kt
Description:
* Added cleaning after interrupted restoration and any different corner cases
> fix: added cleaning up after interrupted restoration

- app/src/androidTest/java/com/tari/android/wallet/FFICommsConfigTests.kt
- app/src/androidTest/java/com/tari/android/wallet/FFITransportTypeTest.kt
- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/aidl/com/tari/android/wallet/model/Model.aidl
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletServiceListener.aidl
- app/src/main/cpp/CMakeLists.txt
- app/src/main/cpp/jniCovenant.cpp
- app/src/main/cpp/jniOutputFeatures.cpp
- app/src/main/cpp/jniTariTransportConfig.cpp
- app/src/main/cpp/jniTransactionSendStatus.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIBase.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIByteVector.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICommsConfig.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFICovenant.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITariTransportConfig.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITransactionSendStatus.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListener.kt
- app/src/main/java/com/tari/android/wallet/ffi/HexString.kt
- app/src/main/java/com/tari/android/wallet/model/TransactionSendStatus.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- build.gradle
Description:
* Updated FFI to 32.3
* Introduced creation TariCovenant and OutputFeature
> feat: update ffi to 32

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/infrastructure/security/biometric/BiometricAuthenticationService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/userAutorization/BiometricAuthenticationViewModel.kt
- app/src/main/res/values/strings.xml
Description:
* Fixed auth error
* Fixed error dialog text and negative button problem
* Fixed crash when wasn't any negative text
* Updated libs
> fix: fixed auth error

- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/UtxosListViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/adapters/UtxosTextListViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/module/UtxoSplitModuleView.kt
Description:
* Fixed 24th suggestion
> fix: seed words fix

- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
Description: 
* Fixed all list hiding state
> Fix: all settings gone list

- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/UtxosListFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/UtxosListViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/controllers/BottomButtonsController.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/controllers/CheckedController.kt
- app/src/main/res/layout/fragment_utxos_list.xml
- app/src/main/res/values/strings.xml
- build.gradle
Description:
0. animate bottom button
1. Select the long press tile when entering select mode
3. Tile scroll lagging when 1 fit and 1 don't fit
4. Wrong success description on the join
5. Fixed bug with looped selection mode state updating
> fix: aligning utxo list with ios

- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/adapters/UtxosTextListViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/adapters/UtxosTileListViewHolder.kt
- app/src/main/res/drawable/background_utxos_list_tile_outline.xml
- app/src/main/res/layout/item_utxos_text.xml
- app/src/main/res/layout/item_utxos_tile.xml
Description:
* Added dimmed state for tile and text utxos list
* Updated tile checked style
> feat: utxos dimmed state

- app/src/main/java/com/tari/android/wallet/tor/TorProxyControl.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyManager.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyState.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/ConnectionIndicatorViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/module/ConnectionStatusesModule.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/torBridges/TorBridgesSelectionViewModel.kt
Description: 
* Split tor running status into running and initializing by bootstrap status
> fix: tor running status fix

- build.gradle
> feat: bump version

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
- build.gradle
Description:
* Fixed 426 error after backuping 
* Updated FFI version to fixed one
> fix: fixed 426 backup error

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFISeedWords.kt
- app/src/main/java/com/tari/android/wallet/model/seedPhrase/SeedPhrase.kt
- app/src/main/java/com/tari/android/wallet/notification/NotificationBroadcastReceiver.kt
- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
- app/src/main/java/com/tari/android/wallet/service/WalletServiceLauncher.kt
- app/src/main/java/com/tari/android/wallet/service/seedPhrase/SeedPhraseRepository.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyManager.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/restore/WalletRestoreActivity.kt
- app/src/main/res/values/strings.xml
- build.gradle
Description:
* Fixed several soft locks related to clicking on the notification
* Fixed FFIService state during the recovering process
* Fixed messed up notifications intent logic
* Fixed problem with no actual using splash screen when user click notification when the app is off
* Fixed problem when the user navigated to the home screen during the recovery process
* Updated minor gradle version
> fix: fixes all notifications problems

- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/delegates/SharedPrefGsonDelegate.kt
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/extension/StringExtensions.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIBase.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/LocalBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/logging/BugReportingService.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/logging/LocalFileAdapter.kt
- app/src/main/java/com/tari/android/wallet/network/NetworkConnectionStateReceiver.kt
- app/src/main/java/com/tari/android/wallet/notification/NotificationBroadcastReceiver.kt
- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
- app/src/main/java/com/tari/android/wallet/service/BootDeviceReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/ServiceRestartBroadcastReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/tor/NativeLoader.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyControl.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyManager.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/common/gyphy/repository/GiphyRESTRetrofitRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/createWallet/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
- app/src/main/java/com/tari/android/wallet/yat/YatAdapter.kt
- app/src/regular/java/com/tari/android/wallet/infrastructure/backup/GoogleDriveBackupStorage.kt
Description:
* Fixed logging problem where Logger.t(tag) tag was used only once per call
* Fixed issue where logging file was rewrited
* Fixed issue where flush happened only once per application launch
* Refactored a bit few places
> fix: logging fixes

- app/src/main/cpp/jniWallet.cpp
- build.gradle
Description:
* Updated FFI version up to 0.38.4
* Updated wallet.h wrapper
> feat: update ffi up to 0.38.4

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListener.kt
- app/src/main/java/com/tari/android/wallet/ffi/TXOValidationStatus.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/res/values/strings.xml
- build.gradle
Description:
* Updated to 0.38.5
* Fixed callback changes
* Updated URL to faucet
* Updated URL to block explorer
> feat: updated to 0.38.5

- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
- build.gradle
Description: 
* Fixed button title on first tari dialog
* Fixed interface incompatibility on one side payment "send_tari"
* Bumped release number
> fix: release 16.0 testing

- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationModule.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/logging/BugReportingService.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/logging/LoggerAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsNavigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/bugReporting/BugReportingNavigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/bugReporting/BugsReportingFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/bugReporting/BugsReportingViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/logs/activity/DebugActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/logs/logFiles/LogFilesFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/logs/logFiles/LogFilesViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/logs/logs/LogsViewModel.kt
- app/src/main/res/layout/fragment_bugs_reporting.xml
- app/src/main/res/values/strings.xml
* Removed old scene
* Added new scene based on good UI and sentry
* Fixed merge problems
> feat: bug reporting scene

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/CMakeLists.txt
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/service/FFIWalletListenerImpl.kt
- app/src/main/java/com/tari/android/wallet/service/service/TariWalletServiceStubImpl.kt
- build.gradle
* Turned off faucet
* Updated up to 0.39.0
> feat: update up to 0.39.0

- app/src/main/cpp/CMakeLists.txt
- app/src/main/cpp/jniCompletedTransaction.cpp
- app/src/main/cpp/jniContact.cpp
- app/src/main/cpp/jniPendingInboundTransaction.cpp
- app/src/main/cpp/jniPendingOutboundTransaction.cpp
- app/src/main/cpp/jniTariWalletAddress.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFICompletedTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIContact.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingInboundTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITariWalletAddress.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITxBase.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/service/TariWalletServiceStubImpl.kt
- build.gradle
* Updated FFI lib up to 0.40.0
* Replaced in several places TariPubKey to TariWalletAddress
> feat: update to 0 40

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/MigrationManager.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupNamingPolicy.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/dropbox/DropboxBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/googleDrive/GoogleDriveBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/local/LocalBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/model/WalletError.kt
- app/src/main/java/com/tari/android/wallet/service/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthNavigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/createWallet/CreateWalletViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/inroduction/IntroductionFragment.kt
- app/src/main/res/values/strings.xml
> fix: added ability to recreate wallet if it's not compatible with network

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/dropbox/DropboxBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/googleDrive/GoogleDriveBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- build.gradle
Aligned backup options corner cases
> fix: 0.17.0 release candidate fixes

- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/service/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/activity/SendTariActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/activity/SendTariViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/EnterCurrentPasswordFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/deleteWallet/DeleteWalletActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/logs/LogFilesManager.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsFragment.kt
* Added files management for log files
> feat: log files manager

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/SharedPrefsRepository.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/data/BackupSettingsRepository.kt
- app/src/main/java/com/tari/android/wallet/util/BuildUtil.kt
- build.gradle
* Updated FFI lib to 0.43.2
* Removed apply and remove encryption error
* Removed database password
* Turn off backuping
> feat: ffi update up to 43 2

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
* Removed tests related to encryption
> fix: test fixes 0.18.0

- app/src/main/res/layout/fragment_create_wallet.xml
- app/src/main/res/layout/fragment_local_auth.xml
- app/src/main/res/layout/fragment_tx_list.xml
- build.gradle
* Fixed a few onboardnig isues
> fix: onboarding fixes release

- app/proguard-rules.pro
- build.gradle
Fixed situation where R8 collects theme name
> fix: fixed crash related to R8

- app/src/main/res/layout/notification_remote_tx.xml
* Fixed lint error when RemoteView not allowed AppCompatImageView
> fix: fix lint remote view

- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/service/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthNavigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListNavigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
* Changed required tor status to Init
* Moved migration check to transaction list screen in order not to wait the wallet
> fix: long startup

- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ui/component/tari/TariBackground.kt
- app/src/main/java/com/tari/android/wallet/ui/component/tari/TariInput.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/ModularDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/extension/ViewExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/activity/WalletRestoreActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxListener.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/YatFinalizeSendTxActivity.kt
- app/src/main/java/com/tari/android/wallet/util/BuildUtil.kt
- app/src/main/res/drawable/vector_close_opposite.xml
- app/src/main/res/drawable/vector_home_store_and_forward_progress_view_bg.xml
- app/src/main/res/layout/activity_qr_scanner.xml
- app/src/main/res/layout/dialog_base.xml
- app/src/main/res/layout/dialog_module_backup_onboarding_flow_item.xml
- app/src/main/res/layout/fragment_backup_onboarding_flow.xml
- app/src/main/res/layout/fragment_tx_list.xml
- app/src/main/res/layout/fragment_wallet_info.xml
- app/src/main/res/layout/item_home_tx_list.xml
- app/src/main/res/layout/tari_input.xml
- app/src/main/res/values/dark_colors_palette.xml
- app/src/main/res/values/light_colors_palette.xml
- app/src/main/res/values/purple_colors_palette.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/tari_elements_attrs.xml
* Fixed broken recovery from seed phrase
* Fixed broken navigation after sending tx
* Fixed glitch with tari input
* Fixed back of dialog
* Fixed backup state when it's was backuping empty wallet 
* Fixed glitch with fee during adding amount
* Fixed shadows
* Fixed button back in disabled state on white theme
> fix: UI fixes

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxFragment.kt
- app/src/main/res/layout/fragment_add_note.xml
- app/src/main/res/layout/fragment_backup_onboarding_flow_item.xml
- app/src/main/res/layout/tari_palette_current_theme.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
* New lint error about Translation_Y field
* Fixed several new warnings and infos
> fix: fixed lint errors

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupFileProcessor.kt
Removed exceeded database encryption in order to align with iOS
> fix: removed database exceeded encryption

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/dropbox/DropboxBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/dropbox/DropboxClientFactory.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonFragment.kt
- build.gradle
* Reselecting new dropbox account
* Clicking through fragments
* Version bump
> fix: release candidate fix

- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupUtxos.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/ModularDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupOnboarding/BackupOnboardingFlowFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupOnboarding/item/BackupOnboardingFlowDataSource.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupOnboarding/item/BackupOnboardingFlowItemFragment.kt
- app/src/main/res/layout/dialog_base.xml
- app/src/main/res/values/styles.xml
- build.gradle
* Fixed SpannableString serialization problem
* Bump version
* Fixed moment when utxos can be null after serialization
> fix: release candidate fixes

- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkFormatter.kt
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/modules/customBaseNodeBody/CustomBaseNodeBodyModuleView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/contactSelection/ContactSelectionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/contactSelection/ContactSelectionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/root/ContactBookFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/root/ContactBookViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/Navigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/TariNavigator.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/qr/QRScannerActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/qr/QRScannerViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/HomeFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TransactionRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TransactionItem.kt
- app/src/main/res/layout/fragment_home.xml
* Aligned functionality with iOS
> feat: ios aligning

- app/src/main/java/com/tari/android/wallet/ui/extension/ParcelableExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/TariNavigator.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/qr/QRScannerActivity.kt
- Add `Intent.serializable(key)` extension
- Replace all `getSerializableExtra` calls in the project with the new extension
> feat: add serializable extension for intent extras

- app/src/main/AndroidManifest.xml
Remove taskAffinity="" and clean up the manifest file
> feat: fix the multiple app's windows issue

- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/HomeFragmentViewModel.kt
- Changed sorting order of txs on the Home Page
> feat: sort last txs on the Home Page reversely

- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- Changed logVerbosity for FFI from 2 to 4
> feat: change logVerbosity for FFI from 2 to 4

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NetworkRepositoryImpl.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/TariNetwork.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- build.gradle
- Updated FFI lib version to `v1.0.0-alpha.1`
- Added missing fields
- Cleared up code
> feat: update FFI lib to v1.0.0-alpha.1

- app/src/main/java/com/tari/android/wallet/application/WalletState.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/splash/SplashActivity.kt
Fixed the state when the default app's network has been changed. Now it restarts the app correctly
> feat: fix switching selected network on start of the app

- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkViewModel.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITxBase.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/bluetooth/TariBluetoothServer.kt
- app/src/main/java/com/tari/android/wallet/model/MicroTari.kt
- app/src/main/java/com/tari/android/wallet/model/TariContact.kt
- app/src/main/java/com/tari/android/wallet/model/TariWalletAddress.kt
- app/src/main/java/com/tari/android/wallet/service/service/TariWalletServiceStubImpl.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/contactSelection/ContactSelectionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/contactSelection/ContactSelectionModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/contactSelection/ContactSelectionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/data/ContactsRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/data/contacts/ContactDto.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/data/contacts/IContact.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/data/contacts/PhoneContactDto.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/data/contacts/YatContactDto.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/root/ShareViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/TariNavigator.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/common/TransactionData.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/YatFinalizeSendTxActivity.kt
- app/src/main/java/com/tari/android/wallet/util/DebugConfig.kt
- app/src/main/java/com/tari/android/wallet/yat/YatAdapter.kt
- Add the possibility to send money not only by wallet address, but also by a Yat name
> feat: Send a transaction using Yat name

- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/event/EventBus.kt
- app/src/main/java/com/tari/android/wallet/extension/FlowExtensions.kt
- app/src/main/java/com/tari/android/wallet/extension/ViewModelExtension.kt
- app/src/main/java/com/tari/android/wallet/tor/TorBootstrapStatus.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyControl.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyManager.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyState.kt
- app/src/main/java/com/tari/android/wallet/tor/TorProxyStateHandler.kt
- app/src/main/java/com/tari/android/wallet/tor/TorResourceInstaller.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/ConnectionIndicatorViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/module/ConnectionStatusesModule.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/createWallet/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/createWallet/CreateWalletModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/createWallet/CreateWalletViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/torBridges/TorBridgesSelectionViewModel.kt
- app/src/main/res/layout/fragment_create_wallet.xml
- app/src/main/res/values/strings.xml
- Added a new state for Tor initialization process when it's ready for wallet creation (on Tor cookie files are created)
- Refactored `TorProxyState` and encapsulate its logic to `TorProxyStateHandler` instead of `EventBus`
> feat: Fix Tor initialization

- app/src/main/java/com/tari/android/wallet/ui/fragment/store/EventsPropagatingWebViewClient.kt
- build.gradle
Added log events for `EventsPropagatingWebViewClient`
> feat: WebView logging

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/common/TransactionData.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- build.gradle
Added the `PaymentID` parameter to the send tari method
> feat: PaymentID

- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/ContactsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/adapter/contact/ContactItemViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/adapter/contact/badges/BadgesController.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/root/actionMenu/ActionMenuView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/root/actionMenu/ContactBookActionMenuViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
- app/src/main/res/layout/activity_home.xml
- app/src/main/res/layout/item_contact.xml
- app/src/main/res/layout/item_contact_old.xml
Align the contact list item layout with the new wallet address format:
> feat: New address format – contact list item

- app/src/main/java/com/tari/android/wallet/model/TariWalletAddress.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/ContactsRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/contacts/ContactInfo.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/adapter/profile/ContactProfileViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/adapter/profile/ContactProfileViewHolderItem.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/row/SettingsRowView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/row/SettingsRowViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/row/SettingsRowViewHolderItem.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/logs/logFiles/adapter/LogFileViewHolder.kt
- app/src/main/res/layout/fragment_contacts_details.xml
- app/src/main/res/layout/item_contact_profile.xml
- app/src/main/res/layout/item_contact_type.xml
- app/src/main/res/layout/item_settings_divider.xml
- app/src/main/res/layout/view_settings_row.xml
- app/src/main/res/layout/view_settings_title.xml
Align the contact details screen layout with the new wallet address format:
> feat: New address format – contact details

- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsViewModel.kt
- app/src/main/res/layout/fragment_add_amount.xml
- app/src/main/res/layout/fragment_add_note.xml
- app/src/main/res/layout/item_thumbnail_gif.xml
Aligned Send Tari screens with the new wallet address format:
> feat: New address format – Send Tari

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/baseNodes/BaseNodesManager.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListener.kt
- app/src/main/java/com/tari/android/wallet/service/baseNode/BaseNodeSyncState.kt
- app/src/main/java/com/tari/android/wallet/service/service/FFIWalletListenerImpl.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/ConnectionIndicatorState.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/ConnectionIndicatorView.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/ConnectionIndicatorViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/module/ConnectionStatusesModule.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/module/ConnectionStatusesModuleView.kt
- app/src/main/res/layout/dialog_module_connection_statuses.xml
- app/src/main/res/layout/view_connection_indicator.xml
- app/src/main/res/values/strings.xml
- build.gradle
Added wallet height label to the connection status dialog
> feat: Wallet height label

- app/src/main/res/layout/fragment_utxos_list.xml
Fixed non-clickable action buttons in the Utxo list screen by making the whole button layout clickable, not just the icon
> feat: Fix inability to break UTXOs

- app/src/main/java/com/tari/android/wallet/model/TariWalletAddress.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/chat/chatList/adapter/ChatItemViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/chat/chatList/adapter/ChatItemViewHolderItem.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/qr/QRScannerViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/HomeFragmentViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/ContactUtil.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
- app/src/main/res/layout/item_chat_item.xml
- app/src/main/res/values/strings.xml
- Replaced short 3-digit emojis in texts with the new format
- Removed unused code
- Hid edit Yat field in the edit contact dialog by the feature flag
> feat: New wallet address format – misc

- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/ContactAction.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/contacts/ContactInfo.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoViewModel.kt
- app/src/main/res/values/strings.xml
- build.gradle
- Added an option to add tx address to contacts
- Made possible to remove only added contacts
- Show an error dialog when the user set an empty name for a contact
- Increased the version of FFI to `v1.2.0-pre.0`
> feat: Fix add/remove contact

- app/src/androidTest/java/com/tari/android/wallet/FFITestSuite.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/FFIContactsRepositoryBridge.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoFragment.kt
- build.gradle
- Fixed the edit contact feature (add a name, remove a contact, add to favorites)
- Updated the FFI lib version to `v1.3.0-pre.0`
> feat: New wallet address format – edit contact

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/application/YatAdapter.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/yat/YatPrefRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/modules/yatInput/YatInputModuleView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contactSelection/ContactSelectionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contactSelection/ContactSelectionModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contactSelection/ContactSelectionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/ContactsRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/contacts/ContactDto.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/contacts/YatDto.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/Navigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/TariNavigator.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizingStepView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/YatFinalizeSendTxActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/res/layout/fragment_wallet_info.xml
- app/src/main/res/layout/view_finalizing_step.xml
Applied changes from the new `0.5.0` Yat lib version and improved Yat code
> feat: Yat lib version 0.5.0

- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/details/ContactDetailsViewModel.kt
Fix the toggle favorite action on the Contact List screen (prevent call toggle action 2 times)
> feat: Fix toggle favorite

- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/data/FFIContactsRepositoryBridge.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxListHomeViewHolder.kt
- build.gradle
- Increased the FFI lib version to `v1.4.0-pre.0`
- Filter Coinbase contacts in the Contact list
- Fixed Coinbase tx item layout
> feat: Coinbase txs bug fixes

- app/src/main/java/com/tari/android/wallet/application/YatAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/myProfile/MyProfileViewHolder.kt
- app/src/main/res/layout/item_my_profile.xml
Aligned the Profile item in the Settings screen with Yat
> feat: Yat rebuilding – Settings screen

- app/src/main/java/com/tari/android/wallet/model/TariWalletAddress.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/address_poisoning/AddressPoisoningChecker.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/HomeFragmentViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/ContactUtil.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
Use the core Tari address for the short address texting instead of the spend key
> feat: Full address in address bar

- app/src/main/java/com/tari/android/wallet/extension/StringExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/CommonTxListViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxListHomeViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxListViewHolder.kt
- app/src/main/res/values/strings.xml
- Added username texts to Coinbase txs 
- Moved common code of tx list view-holders to a superclass
- Fixed bold text style in tx titles
> feat: Coinbase tx username

- app/src/main/java/com/tari/android/wallet/ffi/FFIBase.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsViewModel.kt
Fixed tx status text on the Tx Detail screen.
> fix: Tx status on Tx Detail screen

- build.gradle
- Increased app's version to `0.27.0(303)` 
- Increased FFI lib version (and minimum lib version) to `v1.4.1-rc.0`
> build: Release 0.27.0

- app/src/main/AndroidManifest.xml
Fixed schemes for deeplinks:
- Removed the `https://tari.esmeralda` scheme
- Reorganize Manifest code
> feat: Deeplinks scheme

- app/src/main/java/com/tari/android/wallet/application/MigrationManager.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthViewModel.kt
- build.gradle
- Fixed the issue with the Migration manager version checking
> build: Release 0.27.0(305)

- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoFragment.kt
Fixed the condition for showing Yat address on the Profile screen
> fix: Show wallet address correctly

- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- Added a constructor for creating an FFIWallet instance instead of init a wallet in the `init` block. 
- Fixed DI: pass all the final values required for the wallet creation instead of passing services providing necessary values
> feat: Paper Wallet – FFIWallet constructor

- app/src/main/java/com/tari/android/wallet/application/baseNodes/BaseNodesManager.kt
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkManager.kt
- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/torBridges/TorBridgesSelectionViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/DebugConfig.kt
- Hid the select base nodes feature with a new feature flag
> feat: Paper Wallet – hide Base Nodes selection

- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- build.gradle
Merge the 0.28.1 release branch to the development
> build: Release 0.28.1

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NetworkPrefRepositoryImpl.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/walletRestoring/WalletRestoringViewModel.kt
- build.gradle
Updated the FFI lib version to `v1.7.0-pre.3` and align the code
> feat: Update FFI to Update FFI v1.7.0-pre.3

- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NetworkPrefRepositoryImpl.kt
- build.gradle
Switched to the NextNet network
> build: Switch to NextNet

- app/src/main/java/com/tari/android/wallet/data/tx/TxListData.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/address_poisoning/AddressPoisoningChecker.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- Fixed fee progress bar showing
- Made the Address Poisoning feature to load txs from repository
- Fixed Yat finalizing activity logic
> fix: Lesser bugs

- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletCallbackListener.kt
- app/src/main/java/com/tari/android/wallet/data/tx/TxRepository.kt
- build.gradle
Merge release branch to develop.
- Small hotfixes
> build: Release 0.29.0

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsOptionAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
Skip the Ass Note screen if a QR code contains a prefilled note
> feat: Skip add note screen for TTL QR

- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contactSelection/ContactSelectionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/link/ContactLinkViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/root/ContactBookFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/qr/QrScannerActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/store/StoreFragment.kt
- app/src/main/java/com/tari/android/wallet/util/DebugConfig.kt
- app/src/main/res/layout/item_contact_link_header.xml
- app/src/main/res/values/strings.xml
- Fixed TTL store checkout issue
- Fixed crashes when lateinit values are not initialized
- Fixed text color on the Link Contact screen
- Fixed crash when dialog is trying to hide not on the main thread
- Fixed crash in contact book after contacts linked
> fix: Bug fixes for the next release

- app/src/main/java/com/tari/android/wallet/extension/ViewModelExtension.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/ContactsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/adapter/emptyState/EmptyStateViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/adapter/emptyState/EmptyStateViewHolderItem.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/link/ContactLinkFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/link/ContactLinkModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/link/ContactLinkViewModel.kt
- app/src/main/res/layout/fragment_all_transaction_history.xml
- app/src/main/res/layout/item_contact_link_header.xml
- build.gradle
- Fixed non-readable search text for dark themes
- Refactored the Contact Link screen to handle search events more properly
> fix: Fix link contact screen issues

- app/src/main/java/com/tari/android/wallet/ui/screen/tx/adapter/TxViewHolderItem.kt
- build.gradle
Align the 0.30.1 release branch with the develop
> build: Release 0.30.1

- app/build.gradle.kts
- app/src/main/java/com/tari/android/wallet/ui/common/DialogManager.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/ModularDialog.kt
- buildSrc/src/main/kotlin/BuildConfig.kt
Align the release branch with the development
> build: Release 0.31.0

- app/src/main/cpp/jniCompletedTransaction.cpp
- app/src/main/cpp/jniPendingInboundTransaction.cpp
- app/src/main/cpp/jniPendingOutboundTransaction.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/send/common/TransactionData.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/send/finalize/FinalizeSendTxViewModel.kt
- buildSrc/src/main/kotlin/BuildConfig.kt
Updated the FFI version to the `v1.11.0-rc.0` and aligned the code
> build: Release 0.31.2

- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/backup/BackupPrefRepository.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/dropbox/DropboxBackupStorage.kt
- app/src/main/java/com/tari/android/wallet/ui/common/domain/PaletteManager.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/modules/button/ButtonModuleView.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/onboarding/inroduction/IntroductionScreen.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/restore/chooseRestoreOption/option/RecoveryOptionView.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/settings/backup/backupSettings/option/BackupOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/settings/backup/data/BackupOption.kt
- app/src/main/res/layout/dialog_module_button.xml
- app/src/main/res/layout/fragment_bugs_reporting.xml
- app/src/main/res/layout/fragment_enter_pincode.xml
- app/src/main/res/layout/fragment_local_auth.xml
- app/src/main/res/layout/tari_gradient_button.xml
- app/src/main/res/layout/tari_secondary_button.xml
- app/src/main/res/values/strings.xml
- Disabled the Dropbox backup option 
- Fixed bugs mentioned by QA
> feat: Redesign bugfixes

- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeepLink.kt
- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/data/airdrop/AirdropRepository.kt
- app/src/main/java/com/tari/android/wallet/data/airdrop/AirdropRetrofitService.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/di/GiphyRestModule.kt
- app/src/main/java/com/tari/android/wallet/di/RetrofitModule.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/ui/common/giphy/presentation/GifViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/common/giphy/repository/GiphyRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/common/giphy/repository/GiphyRestService.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/home/overview/HomeOverviewViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/onboarding/activity/OnboardingFlowActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/restore/chooseRestoreOption/ChooseRestoreOptionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/send/addNote/gif/ThumbnailGifViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/tx/details/gif/GifViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/tx/history/all/AllTxHistoryViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/tx/history/contact/ContactTxHistoryViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/DebugConfig.kt
- app/src/main/java/com/tari/android/wallet/util/extension/ViewModelExtension.kt
- app/src/main/res/layout/activity_qr_scanner.xml
- app/src/main/res/layout/fragment_choose_restore_option.xml
- app/src/main/res/values/strings.xml
Added some changes to the Sync speeding-up feature:
- Updated onboarding screens with the new redesigned texts
- Added REST module for the Airdrop API
- Updated Paper Wallet QR parameters
> feat: Speed up sync wallet

- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/data/airdrop/AirdropRepository.kt
- app/src/main/java/com/tari/android/wallet/data/airdrop/AirdropRetrofitService.kt
- app/src/main/java/com/tari/android/wallet/data/push/PushRepository.kt
- app/src/main/java/com/tari/android/wallet/data/push/PushRetrofitService.kt
- app/src/main/java/com/tari/android/wallet/notification/FcmHelper.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/home/HomeViewModel.kt
- Added `userId` to the PUSH registration API
- Added an authorization header to `@GET("/api/miner/status/{id}")` with value of Airdrop token
> feat: PUSH registration 

- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/home/overview/HomeOverviewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/home/overview/HomeOverviewScreen.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/home/overview/HomeOverviewViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/home/overview/widget/BlockSyncChip.kt
- app/src/main/res/drawable/vector_block_synced.xml
- app/src/main/res/values/strings.xml
Added a new  `BlockSyncChip` component to the Home Overview screen
> feat: Block Sync Status

- app/src/main/java/com/tari/android/wallet/data/airdrop/AirdropRepository.kt
- app/src/main/java/com/tari/android/wallet/data/airdrop/AirdropRetrofitService.kt
- app/src/main/java/com/tari/android/wallet/ui/screen/home/overview/HomeOverviewViewModel.kt
Add the `"x-view-key-hashed"` to the `AirdropRetrofitService.getMinerStatus()` method
> feat: View Key to get Miner Status
