tari-project/wallet-android

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/cpp/jniPendingOutboundTransaction.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIPendingOutboundTx.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITestWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- jniLibs/wallet.h
Fixed jni methods for getting transactions by id accepting long instead of BigInteger
Added additional methods to JNI:
1) Get fee for outbound transaction
2) Check if completed transaction was originally outbound transaction
Updated tests
Updated header
> Fixed JNI methods accepting long instead of BigInteger, added additional methods to JNI

- .gitignore
The 64bit binaries are too large to be included in the source code,
and are brought in by hand (built or downloaded)
so the jniLibs folder should be added to .gitgnore
> Ignore jniLibs

- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateEmojiIdFragment.kt
Fixes an issue where onAnimationEnd is not called on lower android versions.
> Fix check mark animation issue in v24

- app/src/main/aidl/com/tari/android/wallet/service/TariWalletService.aidl
- app/src/main/cpp/jniPublicKey.cpp
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIPublicKey.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/java/com/tari/android/wallet/util/DateExtensions.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
Set constant emojiIdLength = 13
Removed getPublicKeyForEmojiId
Removed Java_com_tari_android_wallet_ffi_FFIPublicKey_jniGetEmoji
Removed constructor(emoji: String) : this(nullptr) from FFIPublicKey
Added Java_com_tari_android_wallet_ffi_FFIPublicKey_jniGetEmojiNodeId
Added public_key_to_emoji_node_id
Added getEmojiNodeId()
Commented out clipboard code in AddRecipientFragment
Fixed deprecated java method
> Updated wallet for FFI changes

- app/src/main/java/com/tari/android/wallet/model/QRScanData.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/util/WalletUtil.kt
Fixes #70
Changes:
- Use QR scanner activity to allow adding recipient by scanning QR code.
> Sending Tari: Adding a recipient by QR Code

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/aidl/com/tari/android/wallet/service/TariTorService.aidl
- app/src/main/aidl/com/tari/android/wallet/service/TariTorServiceListener.aidl
- app/src/main/cpp/jniTransportType.cpp
- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/di/TorModule.kt
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIByteVector.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFITransportType.kt
- app/src/main/java/com/tari/android/wallet/service/TorService.kt
- app/src/main/java/com/tari/android/wallet/util/AppUtil.kt
- build.gradle
Closes #131
Changes:
- Integrates TOR proxy and run it in a separate process. I think running it in a separate process should be fine as we are binding it forever from the main app process. However, if there are instances where it keeps getting killed by android system, we should move it to the main process.
TODO:
- Use Tor config in wallet initialization. Currently, it's done in module but we will need to do it outside as we need hashed password of Tor, which will be available once Tor service starts and gets binded to app.
> Integrate Tor proxy

- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/log/DebugLogActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/BaseFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/log/DebugLogFilePickerFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/log/DebugLogFragment.kt
- app/src/main/java/com/tari/android/wallet/util/WalletUtil.kt
- app/src/main/res/drawable/ic_more_vert_black_24dp.xml
- app/src/main/res/layout/activity_debug_log.xml
- app/src/main/res/layout/fragment_debug_log.xml
- app/src/main/res/layout/fragment_log_file_list.xml
- app/src/main/res/values/strings.xml
Closes #139
Changes:
- Save each app run logs in a different file
- Add log display fragment
- Add log picker fragment
> Separate log files for each run

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/di/ApplicationComponent.kt
- app/src/main/java/com/tari/android/wallet/service/BootDeviceReceiver.kt
Closes #136 
Changes:
- Add boot event receiver and start wallet service on boot event callback.
> Start the wallet service at OS boot time

- app/src/main/java/com/tari/android/wallet/ui/util/UiUtil.kt
The QR encoding library uses ISO-8859-1 as the default character set,
which meant that emoji were encoded as "?" characters. This PR tells the
library to use UTF-8 as the character set so that emojis are encoded
correctly.
> Fix QR encoding bug

- app/src/main/java/com/tari/android/wallet/di/ApplicationModule.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
Closes #172
Uses android platform ICU lib and gets rid of integrated library, this should reduce APK size by ~9mb.
> Fix add recipient fragment crash on lower android versions

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
Fixed loop bug for completed tx in FIWalletTests
Fixed bug for pending outbound txs in FFIWalletTests.
> Wallet Test

- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/profile/WalletInfoActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/send/SendTariActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/BottomSlideDialog.kt
- app/src/main/java/com/tari/android/wallet/ui/extension/ViewExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/IntroductionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/LocalAuthFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/util/UiUtil.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/res/anim/dialog_slide_from_bottom.xml
- app/src/main/res/anim/dialog_slide_to_bottom.xml
- app/src/main/res/drawable/wallet_info_bg_qr_code_image_dimmer.xml
- app/src/main/res/layout/activity_tx_detail.xml
- app/src/main/res/layout/activity_wallet_info.xml
- app/src/main/res/layout/fragment_add_amount.xml
- app/src/main/res/layout/fragment_add_note.xml
- app/src/main/res/layout/fragment_add_recipient.xml
- app/src/main/res/layout/fragment_create_wallet.xml
- app/src/main/res/layout/fragment_introduction.xml
- app/src/main/res/layout/fragment_local_auth.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Add press animation to the wallet creation button
Set CIRC_IN_OUT interpolation for white background appearance
Remove shadow from "Create Your Emoji ID" button
Add QUINT_IN interpolation to the "Secure Your Wallet" scene
Remove dead imports from Constants.kt
Remove shadow from "Secure with ?" button
Add CIRC_IN_OUT easing to home page draggable view onboarding showup
Style "testtari received" dialog to slide from bottom to the target position
Lower the header with back button and text for Add Recipient, Add Amount, Add Note pages
Make store dialog appeared as sliding from bottom
Update all application bottom dialogs to slide from the bottom
Make `Continue` button visible after wallet creation borderless
Incorporate expandable/collapsible emoji id to the Wallet Info page
> Ticket 267 (QA Notes)

- app/src/main/java/com/tari/android/wallet/ui/activity/home/CustomScrollView.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/onboarding/OnBoardingFlowActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/CreateWalletFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/FinalizeSendTxFragment.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/res/layout/activity_home.xml
Displays the continue button after emoji id view is maximized during onboarding tari-project/wallet-android#153. Adds new Matomo events tari-project/wallet-android#271.  Transaction list minor UI fixes
> Onboarding continue button timing fix & new Matomo events.

- app/src/main/java/com/tari/android/wallet/notification/NotificationHelper.kt
Foreground service notification now takes the user to the application on click per tari-project/wallet-android#321.
> Fixes foreground service notification click behavior.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
Takes the user to the debug screen when they shake the device per tari-project/wallet-android#319.
> Shake device to go to the debug screen.

- app/src/main/java/com/tari/android/wallet/ui/activity/home/CustomScrollView.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/extension/ViewExtensions.kt
Steps to reproduce the issue that's fixed:
- On a transaction list that overflows the screen, first maximize the list.
- Make a fling scroll up.
- While the fling is running, tap on the list and scroll it down to minimized state (either complete the scroll or let the UI complete it).
- You'll find that the list remains scrolled and the elevation shadow remains.
Example:
> Fix for a transaction list interaction bug.

- app/src/main/java/com/tari/android/wallet/model/MicroTari.kt
Scale needed to be specified for division since BigDecimal keeps track of both precision and scale.
> BigDecimal Rounding

- app/src/main/java/com/tari/android/wallet/ui/activity/profile/WalletInfoActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/tx/TxDetailActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddNoteFragment.kt
Copies wallet public key hex string on long click on the Copy Emoji ID button with all emoji id views, per #tari-project/wallet-android#335.
> Copy wallet public key hex on long click on the Copy Emoji ID button

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/FinalizeSendTxFragment.kt
- app/src/main/res/values/strings.xml
Internet connection and Tor bootstrap status are checked in the first step of the sending progress, if these two conditions are met the code relies on the FFI callbacks for any errors that could happen during the send flow.
> Removes base node sync check from sending Tari screen.

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/TariWalletApplication.kt
- app/src/main/java/com/tari/android/wallet/service/BootDeviceReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/ServiceRestartBroadcastReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/AuthActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/SplashActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/IntroductionFragment.kt
- app/src/main/java/com/tari/android/wallet/util/WalletUtil.kt
Moves wallet initiation logic to the service layer to fix a bug that caused the device boot receiver to crash while trying to start the service on device boot.
> Fixes a bug & structural improvement by moving wallet manager from application to wallet service.

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/ui/component/EmojiIdSummaryViewController.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/notification/CustomTxNotificationViewHolder.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
Removes IBM ICU library dependency, relies on the Tari emoji set instead: tari-project/wallet-android#172. Solution implemented for tari-project/wallet-android#172.
> An update for emoji processing - removes IBM ICU library and relies on the Tari emoji set. Improves add recipient screen clipboard check.

- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
Makes use of the `FFIWallet.isCompletedTxOutgoing` function to determine the direction of a completed transaction instead of comparing destination/source keys.
> Improves direction (in/out) determination for completed transactions.

- app/src/main/cpp/CMakeLists.txt
- app/src/main/cpp/jniEmojiSet.cpp
- app/src/main/cpp/jniSeedWords.cpp
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIEmojiSet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFISeedWords.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
This commit adds the ability to the FFI to switch power modes, getting the current emoji set and getting the seed words.
Requires the latest lib build.
> FFI Update

- app/build.gradle
- app/src/main/cpp/CMakeLists.txt
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/util/EmojiUtil.kt
- app/src/main/res/layout/fragment_add_recipient.xml
- app/src/main/res/layout/incompatible_emoji_id_dialog.xml
- app/src/main/res/values/strings.xml
- download-jni-binaries.gradle
Display warning when a user enters Add Recipient screen with an incompatible (i.e. old) emoji id in their clipboard, or when they paste an incompatible emoji id into the text field per tari-project/wallet-android#422.
> Incompatible Emoji ID Warning

- app/src/regular/java/com/tari/android/wallet/infrastructure/security/encryption/SymmetricEncryptionAlgorithm.kt
tari-project/wallet-android#429
Set AES key size to 256 bit and change digest algorithm to SHA-256
Implement CBC block cipher mode
Salt the password used to derive the AES key
Change key derivation algorithm to PBKDF2 and hashing to HMAC-SHA1
Add a decryption routine to the AES
> Add CBC BC, salting and decryption routine to the AES implementation

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/ui/activity/home/HomeActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/home/UpdateProgressViewController.kt
- app/src/main/java/com/tari/android/wallet/ui/activity/settings/SettingsActivity.kt
- app/src/main/res/layout/dialog_backup_wallet_prompt.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
tari-project/wallet-android#408
Implement wallet backup prompts on the home page
Fix the all settings -> backup settings fragments as well as activities' issue
Set explicit dialog buttons' height
Fix layout for backup prompts and title spanning
Allow state loss for after-auth fragments
> Home page wallet backup prompts on TX recieve

- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/ChangeSecurePasswordFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/EnterCurrentPasswordFragment.kt
- app/src/main/res/layout/fragment_change_secure_password.xml
- app/src/main/res/layout/fragment_enter_restore_password.xml
- app/src/main/res/values/strings.xml
- app/src/regular/res/values/strings.xml
Change strings for the backup settings entries
Disable restore wallet and verify current password buttons if input field is empty
Revert restore CTA disabling on empty text field as backup might not have a password
Make text labels denoting input fields on the ChangeSecurePasswordFragment red in case of error as well
> Backup & Restore UI fixes according to the Natasha's comment in tari-project/wallet-android#429

- .github/workflows/release-workflow.yml
- app/build.gradle
- build.gradle
- distribution/whatsnew-en-US
Adds the GitHub Actions workflow that builds bundles, signs them, creates the GitHub release, uploads APKs to browserstack and created a new Play Store beta release. Updates build number, adds release notes for v0.3.0. Some library updates. Distributes APK/AAB files per #368.
> CI Release Workflow

- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- build.gradle
Fixes a regression where a cancelled transaction with a contact did not display contact's name but just the emoji id.
> Fix regression: display contact name for a cancelled tx with a contact.

- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxListAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxViewHolder.kt
- app/src/main/res/values/strings.xml
Display pending transactions first in the transaction list. Fixes an issue caused a wrong display in transaction list for outbound transactions.
>  Fix ordering and a display bug in transaction list.

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/di/TorModule.kt
- app/src/main/java/com/tari/android/wallet/di/WalletModule.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/BugReportingService.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/java/com/tari/android/wallet/util/WalletUtil.kt
- app/src/main/res/values/strings.xml
- build.gradle
Updates to FFI lib `0.16.1`, which introduces rolling log files. Fixes Tor port to `18101`. Bump build and version numbers.
> FFI 0.16.2 update & fixed Tor port 

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddRecipientFragment.kt
Solution for the bug that caused the app to crash when you delete a first l from the text input in the add recipient screen. Related to tari-project/wallet-android#606.
> Add recipient search input text "l" delete crash fix: #606.

- app/src/main/cpp/CMakeLists.txt
Updates cmake to include OpenSSL libraries to be compatible with the latest wallet library.
Linked to PR https://github.com/tari-project/tari/pull/2461
> SSL Dependency

- app/src/main/aidl/com/tari/android/wallet/service/TariWalletService.aidl
- app/src/main/cpp/CMakeLists.txt
- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/util/WalletUtil.kt
- build.gradle
Added estimateTxFee to FFIWallet.
Added jniEstimateTxFee to FFIWallet private method linking to JNI.
Added jniEstimateTxFee to jniWallet.cpp.
Removed `walletutil.calculatetxfee`.
Added `walletservice.estimatetxfee`.
Updated AIDL.
Updated calculatetxfee with estimatetxfee where applicable.
Updated cmake minimum version.
Linked to PR:
Linked to PR: https://github.com/tari-project/tari/pull/2526
> Wallet Library - Estimate tx fee

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
Added jniMethods to get and set the number of required confirmations for the wallet.
Added methods to the wallet class to expose this functionality to Kotlin from the JNI.
Linked to PR:
https://github.com/tari-project/tari/pull/2624/
> Added confirmation settings

- app/build.gradle
- app/src/regular/java/com/tari/android/wallet/di/BackupAndRestoreModule.kt
- app/src/regular/java/com/tari/android/wallet/infrastructure/backup/GoogleDriveBackupStorage.kt
- build.gradle
1. Updated target build tools version up to 30
2. Fixed build warning related to viewBindings. The current way of the declaration was obsolete in the last version
3. Fixed build warning related to unsecured URL to maven
4. Updated UI libraries + dagger + tests + kotlin
5. Updated sentry library because it had an issue with showing a nice error message. It was caused impossible to find a build mistake.
6. Fixed regular flavor build
7. Bumped version number
> Library updates and build fixes

- app/src/main/java/com/tari/android/wallet/tor/TorProxyManager.kt
Unexpected behavior on tor client. It's crashed when the connection is closing on android under 8.0. Higher is ok
Just muted IO exception because it's not useful here and consistent with flow logic
> fix: tor crash

- app/build.gradle
- build.gradle
Description:
Fixed problem with sentry proguard which appears because of last gradle update
https://issueexplorer.com/issue/getsentry/sentry-android-gradle-plugin/70
> fix: fixed sentry proguard vs gradle 7.0 problem

- app/build.gradle
Description:
* Disabled lint checking for new api calls because bitrise has an old version of lint with a bug in this case. In fact on 24 and 29 versions all works the same
> fix: lint new api problems

- app/src/androidTest/java/com/tari/android/wallet/FFIWalletTests.kt
- app/src/main/aidl/com/tari/android/wallet/service/TariWalletServiceListener.aidl
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/SharedPrefsRepository.kt
- app/src/main/java/com/tari/android/wallet/event/Event.kt
- app/src/main/java/com/tari/android/wallet/event/EventBus.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWalletListener.kt
- app/src/main/java/com/tari/android/wallet/service/service/FFIWalletListenerImpl.kt
- app/src/main/java/com/tari/android/wallet/service/service/WalletService.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/inputSeedWords/InputSeedWordsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/activity/SendTariActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientListener.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientNavigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addRecepient/AddRecipientViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/TxListViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/utxos/list/UtxosListViewModel.kt
- build.gradle
Description:
* Added balance update listener
* Fixed updating list itself and after splitting\breaking coins
* Moved faucet txs from completed to pending
* Fixed block explorer link
* Fixed "Completing final transactions **" label for one side payments and payments from the faucet
* Fixed keyboard on restoring from seed phrase
* Added passing value from requesting into the amount screen
> fix: test session fixes

- app/src/main/cpp/jniWallet.cpp
- app/src/main/java/com/tari/android/wallet/application/baseNodes/BaseNodes.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NetworkRepositoryImpl.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/res/raw/nextnet_base_nodes.txt
- build.gradle
- Update the FFI lib to "v1.0.0-rc.1"
- Switch the network to NextNet
- Add list of base nodes for the NextNet network
> feat: prepare NextNet network

- app/src/main/java/com/tari/android/wallet/ffi/HexString.kt
There was a problem when addresses with 1-digit first HEX character were converted without "0".
For example `🌋` emoji has a "04" hex representation, but was converted as "4".
- Forced to keep 2 characters for every byte of wallet address for String conversion.
- Cleaned up constructor code of the `HexString` class
> feat: fix wallet address conversion to String

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/securityStage/StagedWalletSecurityManager.kt
- app/src/main/java/com/tari/android/wallet/event/EffectChannelFlow.kt
- app/src/main/java/com/tari/android/wallet/extension/FlowExtensions.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupManager.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/backup/BackupsState.kt
- app/src/main/java/com/tari/android/wallet/ui/extension/FragmentExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/Navigation.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/TariNavigator.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionState.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/option/RecoveryOptionView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/option/RecoveryOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/enterRestorationPassword/EnterRestorationPasswordFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/enterRestorationPassword/EnterRestorationPasswordModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/enterRestorationPassword/EnterRestorationPasswordViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupSettings/BackupSettingsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupSettings/BackupSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupSettings/option/BackupOptionModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupSettings/option/BackupOptionView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupSettings/option/BackupOptionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/data/BackupOptionDto.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/data/BackupOptionType.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/data/BackupSettingsRepository.kt
The first iteration of the fix of the Backup feature.
I prepared code for further refactoring and bug fixing:
- Moved domain logic out from views to viewModels
- Made classes more stateless by passing required inputs as arguments instead of storing them in third-party classes
And also made some enhancements:
- Added some useful extension functions
- Renamed some classes and variables meaningfully (e.g. `BackupOptions` -> `BackupOptionType` because it is an enum with possible option types)
- Made log messages more informative
- Made some nullable values null-safe
- Moved view state variables to separate immutable UiState classes
Notes:
- I left some TODOs required for continuation of my work
> feat: refactor backup related code

- app/src/main/java/com/tari/android/wallet/application/securityStage/StagedWalletSecurityManager.kt
- app/src/main/java/com/tari/android/wallet/event/EffectChannelFlow.kt
- app/src/main/java/com/tari/android/wallet/event/EventBus.kt
- app/src/main/java/com/tari/android/wallet/extension/AnyExtensions.kt
- app/src/main/java/com/tari/android/wallet/extension/DateExtensions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/backup/backupOnboarding/item/BackupOnboardingArgs.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/HomeFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/HomeFragmentViewModel.kt
Fix the multiple staged wallet security dialog bug
- Fix the wrong date comparison
- Fix the memory leak when `StagedWalletSecurityManager` held an instance of a balance check event subscription even when the app stops
- Make `StagedWalletSecurityManager` a singleton and move all display logic to the VM
- Got rid of the `balanceUpdates` event bus event
- Added a couple of useful utils
- Cleaned up the code
> feat: staged security dialog fix

- Gemfile.lock
- app/build.gradle
- build.gradle
- returned the old way of uploading ProGuard mappings to Sentry
> feat: release/0.25.2

- app/build.gradle
- app/src/main/java/com/tari/android/wallet/application/MigrationManager.kt
- build.gradle
- Added the `LIB_WALLET_MIN_VALID_VERSION` field in the BuildConfig
- Updated min. valid FFI version to 1.0.0-rc.5
> feat: min. valid FFI version to 1.0.0-rc.5

- app/src/main/java/com/tari/android/wallet/application/baseNodes/BaseNodes.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/localAuth/LocalAuthFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/localAuth/LocalAuthViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/onboarding/localAuth/SecureState.kt
- Fixed the baseNodeList issue
- Fixed the not added to activity issue
- Fixed the update LiveData in the background thread issue
> feat: fix sentry errors

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/keyboard/KeyboardController.kt
#1042 
- Fixed issue when the first number of an entered amount was skipped
> feat: fix invalid amount to send on sending money using QR code

- app/src/androidTest/java/com/tari/android/wallet/application/DeepLinkTest.kt
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeepLink.kt
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkFormatter.kt
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkViewModel.kt
- app/src/main/java/com/tari/android/wallet/di/ApplicationModule.kt
- app/src/main/java/com/tari/android/wallet/di/PresentationModule.kt
- app/src/main/java/com/tari/android/wallet/infrastructure/bluetooth/TariBluetoothServer.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/data/ContactsRepository.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/data/contacts/ContactDto.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contact_book/root/ContactBookViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/profile/WalletInfoViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/ContactUtil.kt
- app/src/main/res/values/strings.xml
- Fix wrong parameters in method calls
- Added default alias for users without any: `"Aurora user %s"`
- Create the `ContactUtil` helper class
- Format code
> feat: fix crash on sending contacts using QR code

- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsViewModel.kt
- app/src/main/java/com/tari/android/wallet/util/DebugConfig.kt
- app/src/main/res/values/strings.xml
- Added new Nextnet block explorer config
- Removed `DebugConfig.isBlockExplorerEnabled` flag
- Enable the block explorer feature
> feat: new Nextnet block explorer

- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/NetworkRepositoryImpl.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/network/TariNetwork.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsViewModel.kt
- app/src/main/res/values/strings.xml
- build.gradle
[#1086](https://github.com/tari-project/wallet-android/issues/1086)
- Added the `blockExplorerUrl` field to the Network class and hide the Block Explorer feature if it's null for the selected network
- Updated the FFI lib version to `v1.0.0-alpha.2`
> feat: Block Explorer per network

- app/src/main/java/com/tari/android/wallet/application/MigrationManager.kt
- app/src/main/java/com/tari/android/wallet/ui/common/SimpleViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/auth/AuthViewModel.kt
- Perform Peer DB Migration if app FFI lib's version is higher than `1.0.0-rc.8`
- fix threading issue in `MigrationManager`
> feat: peer DB migration

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/common/DialogManager.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/confirm/ConfirmDialogArgs.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/ModularDialogArgs.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/screenRecording/ScreenRecordingSettingsFragment.kt
- app/src/main/res/values/strings.xml
Added the Screen Recording Disabled dialog (the feature is available for Android 14+ only)
> feat: Screen recording disabled dialog

- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsOptionAdapter.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/AllSettingsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/myProfile/MyProfileViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/allSettings/myProfile/MyProfileViewHolderItem.kt
- app/src/main/res/layout/item_my_profile.xml
- app/src/main/res/layout/item_settings_backup_option.xml
- app/src/main/res/layout/item_settings_version.xml
Aligned the Settings header layout with the new wallet address format:
> feat: New address format – Settings screen

- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/modules/shortEmoji/ShortEmojiModuleView.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/link/adapter/link_header/ContactLinkHeaderViewHolder.kt
- app/src/main/res/layout/dialog_module_short_emoji.xml
- app/src/main/res/layout/item_contact_link_header.xml
- app/src/main/res/values/strings.xml
Aligned the Link Contact screens with the new wallet address format:
> feat: New address format – Link Contact

- app/src/main/cpp/jniCompletedTransaction.cpp
- app/src/main/java/com/tari/android/wallet/ffi/FFICompletedTx.kt
- app/src/main/java/com/tari/android/wallet/model/CancelledTx.kt
- app/src/main/java/com/tari/android/wallet/model/CompletedTx.kt
- app/src/main/java/com/tari/android/wallet/model/PendingInboundTx.kt
- app/src/main/java/com/tari/android/wallet/model/PendingOutboundTx.kt
- app/src/main/java/com/tari/android/wallet/model/Tx.kt
- app/src/main/java/com/tari/android/wallet/model/TxNote.kt
- app/src/main/java/com/tari/android/wallet/ui/common/gyphy/presentation/GifViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxListHomeViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/adapter/TxListViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/details/TxDetailsFragment.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/tari/android/wallet/ui/presentation/TxNoteTest.kt
[#1182](https://github.com/tari-project/wallet-android/issues/1182)
Now we use the `paymentId` field as the note for one-sided txs.
> feat: Payment ID for note

- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contactSelection/ContactSelectionViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/ContactsFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/ContactsViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/FavoritesFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/adapter/contact/ContactlessPaymentItem.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/contacts/adapter/contact/ContactlessPaymentItemViewHolder.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/contactBook/root/ContactBookFragment.kt
- app/src/main/java/com/tari/android/wallet/util/Constants.kt
- app/src/main/res/layout/item_contactless_payment.xml
[#1172](https://github.com/tari-project/wallet-android/issues/1172)
Fixed view item list on screens with contact list:
- Removed the Bluetooth Connect button from the Contact Book screen
- Fixed the empty state view
- Cleaned up the code
> feat: Remove BLE button from contact list

- app/src/main/java/com/tari/android/wallet/ui/common/CommonActivity.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/common/CommonViewModel.kt
Don't hide dialogs on destroying activity. Sometimes it comes to race condition and necessary dialogs are dismissed prematurely
> fix: Don't hide dialogs

- app/src/main/java/com/tari/android/wallet/application/baseNodes/BaseNodesManager.kt
- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletManager.kt
- app/src/main/java/com/tari/android/wallet/data/sharedPrefs/baseNode/BaseNodePrefRepository.kt
- app/src/main/java/com/tari/android/wallet/event/EventBus.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/network/NetworkConnectionStateHandler.kt
- app/src/main/java/com/tari/android/wallet/network/NetworkConnectionStateReceiver.kt
- app/src/main/java/com/tari/android/wallet/service/baseNode/BaseNodeStateHandler.kt
- app/src/main/java/com/tari/android/wallet/ui/component/networkStateIndicator/ConnectionIndicatorViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/TariNavigator.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/finalize/FinalizeSendTxViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/baseNodeConfig/changeBaseNode/ChangeBaseNodeViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/settings/themeSelector/ThemeSelectorViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/tx/HomeFragment.kt
- build.gradle
- Created handlers for the network connection state, base node state, and base node sync state instead of handling them by `EventBus`
- Fixed calling base node sync multiple times simultaneously 
- Don't save the base node state to shared prefs, refresh this value every start instead
- Fixed the call from FFI thread issue while calling the Wallet inside of a wallet callback block
> feat: Paper Wallet – wallet sync status handling

- app/src/main/cpp/jniSeedWords.cpp
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeepLink.kt
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkManager.kt
- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkParser.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFISeedWords.kt
- app/src/main/java/com/tari/android/wallet/ui/dialog/modular/ModularDialogArgs.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/restore/chooseRestoreOption/ChooseRestoreOptionViewModel.kt
- app/src/main/res/values/strings.xml
Changed the format for paper wallet QR: 
- Parse a private key value
- Ask the user to enter the passphrase
- Create a list of seed words using private key and passphrase
- Show an error dialog if the passphrase is incorrect
> feat: Paper Wallet – private key QR

- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkParser.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/home/navigation/TariNavigator.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/common/TransactionData.kt
Use the note value from the QR code deeplink for sending a tx as a prefilled value
> fix: No tx note from QR data

- app/src/main/java/com/tari/android/wallet/application/deeplinks/DeeplinkParser.kt
- build.gradle
- Fixed parsing the `#` (`%23`) character by not decoding URL before parsing deeplink parameters
> fix: Wrong parsing of number sign in deeplinks

- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addNote/AddNoteFragment.kt
Enable the slider on the Add Note screen if the note present as an argument
> fix: Slider is disable if note isn't empty

- app/src/main/aidl/com/tari/android/wallet/service/TariWalletService.aidl
- app/src/main/java/com/tari/android/wallet/extension/WalletExtension.kt
- app/src/main/java/com/tari/android/wallet/ffi/FFIWallet.kt
- app/src/main/java/com/tari/android/wallet/model/TariWalletAddress.kt
- app/src/main/java/com/tari/android/wallet/service/service/TariWalletServiceStubImpl.kt
- app/src/main/java/com/tari/android/wallet/service/service/TariWalletServiceStubProxy.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountFragment.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/AddAmountViewModel.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/FeePerGramOptions.kt
- app/src/main/java/com/tari/android/wallet/ui/fragment/send/addAmount/keyboard/KeyboardController.kt
- app/src/main/res/drawable/tari_switch_compat_selector_track.xml
- app/src/main/res/layout/fragment_add_amount.xml
- app/src/main/res/layout/view_numpad.xml
- Disabled the OSP switcher on the Add Amount screen if there is an address which is one-sided only
- Added touch event animations for the Numpad
- Moved the fee calculation logic from `WalletService` to `FFIWallet`
- Fixed improper progress state while fee is being calculated
> feat: Disable interactive payments for OSP QR

- app/src/main/java/com/tari/android/wallet/model/Tx.kt
- app/src/main/java/com/tari/android/wallet/model/TxNote.kt
Fixed empty note on the Tx detail screen
> fix: Empty note on Tx Detail

- app/proguard-rules.pro
- app/src/main/java/com/tari/android/wallet/application/walletManager/WalletCallbackListener.kt
Added `WalletCallbackListener` to ProGuard rules
> fix: NoSuchMethodError on start wallet
